### ISSUE TITLE
Missing attributes in bundle configuration

### ISSUE THREAD

**Issue by simoncarre** [textmaster/akeneo-extension#52]
Hello,

I have issue with bundle usage. In **System / Configuration / TextMaster**, I can choose only 2 attributes in **Attributes** field :
![capture_001](https://user-images.githubusercontent.com/1229419/75434088-4e5a8680-5951-11ea-8089-11e9f8d0a6d1.png)

But I have many more attributes with type text or textare but they do not appear (for example `description_web`). Do you have an idea?

![capture_002](https://user-images.githubusercontent.com/1229419/75434246-8a8de700-5951-11ea-8f59-407e0b2aea10.png)

Thank you in advance!

Akeneo version: **EE 3.2.28**
Bundle version: **3.2.3**

**Comment by simoncarre** [comment]
After few minutes research it seems that is the `SearchableRepositoryInterface::FETCH_LIMIT` default value (20) in `Akeneo\Pim\Structure\Bundle\Controller\InternalApi\AttributeController\AttributeController`
![capture_001](https://user-images.githubusercontent.com/1229419/75435416-44d21e00-5953-11ea-88d6-4b00a37815d1.png)

Can you fix the bundle to bypass this limit?

Thank you in advance!

**Comment by huynguyen93** [comment]
Thanks a lot for reporting this, we're fixing it now!

**Comment by huynguyen93** [comment]
Hi @simoncarre, we fixed the issue!

You can update our package version now, the new version is 3.2.4.

After upgrading, make sure you have new asset built by running: `./bin/docker/pim-front.sh` and clear the browser cache.

Thanks a lot!

**Comment by simoncarre** [comment]
Thank you for your quick fix!
