### ISSUE TITLE
Unfortunately the current version (4.0.*) cannot be installed!

### ISSUE THREAD

**Issue by tdoedtmann** [textmaster/akeneo-extension#61]
When running `composer require textmaster/akeneo-extension` the tag `v3.2.5` is checked out.
Also an adjustment of _composer.json_ to `"textmaster/akeneo-extension": "~4.0"` does not work, because `"minimum-stability": "stable"` is defined at the same time.

Attempt to install with `composer require ...`:
![Screensho_textmaster_require_command](https://user-images.githubusercontent.com/1023513/80340350-c44f7100-8860-11ea-8ca0-b4b0563821f1.png)

Attempt to install with `composer update ...`:
![Screensho_textmaster_update_command](https://user-images.githubusercontent.com/1023513/80340364-cc0f1580-8860-11ea-8711-007f29a814cd.png)

**Comment by huynguyen93** [comment]
@tdoedtmann , 
Thanks for reporting this. I'm trying to reproduce this issue on a fresh Akeneo 4.0 installation.

**Comment by huynguyen93** [comment]
@tdoedtmann 
Unforunately textmaster/akeneo-extension 4.0 is not officially released.

We're still working on testing this new version. Maybe you can install it in a few days.
You can check it here: https://packagist.org/packages/textmaster/akeneo-extension, to know when the version 4.0 is released.

Thank you!

**Comment by huynguyen93** [comment]
@tdoedtmann 
textmaster/akeneo-extension 4.0 is now released.
Can you try again with: `php -d memory_limit=-1 /usr/local/bin/composer require textmaster/akeneo-extension ~4.0`

Thank you !

**Comment by tdoedtmann** [comment]
@huynguyen93 

Unfortunately the description/installation instructions in your README are not correct.

Maybe you write, like when registering the bundle, that it belongs in the `config/routes/routes.yml`.
In addition, the block with updating the database and regenerating the cache is also incorrect. This is how it worked for me:
```
rm -rf var/cache/* public/js/* public/css/* public/bundles/*
bin/console --env=prod doctrine:schema:update --force
bin/console --env=prod p:i:a --symlink
node yarn run webpack
```

Thank you!

**Comment by huynguyen93** [comment]
@tdoedtmann  you're right, I'm sorry about the wrong instructions !
I will update it.

I close this issue now, if you still have issue installing our package, feel free to reopen this. Thank you !
