### ISSUE TITLE
Extension install problems on clean Akeneo 4.0 on Docker setup

### ISSUE THREAD

**Issue by kilis** [textmaster/akeneo-extension#68]
Hello!

I am trying to install Textmaster Akeneo extension in Akeneo 4.0.6 on docker Setup and i couldn't get it working.
Here are steps what i did to try to install it on local machine with docker setup.
**Perquisites:** 
1. Have docker installed
2. Increase docker swap to 1.5 GB

**How reproduce** 
1. Clone Akeneo setup for version `git clone git@github.com:akeneo/pim-community-dev.git`
2. Checkout version `git checkout v4.0.6`
3. Build docker containers `make pim-dev`
4. Add extension via composer `docker-compose run --rm php php -d memory_limit=-1 /usr/local/bin/composer require textmaster/akeneo-extension:~4.0`
5. Add line to bundle file config/bundles.php
```
<?php

return [
    // Add your bundles here with the associated env.
    // Ex:
    // Acme\Bundle\AppBundle\AcmeAppBundle::class => ['dev' => true, 'test' => true, 'prod' => true]
    Pim\Bundle\TextmasterBundle\PimTextmasterBundle::class => ['dev' => true, 'test' => true, 'prod' => true],
];
```
5. Clean folders for cache and other static content `rm -rf pub/bundles pub/cache pub/css pub/js`
6. Run schema update `docker-compose run -u www-data --rm php bin/console doctrine:schema:update --force --env=dev`
7. Run pim installer assets `docker-compose run -u www-data --rm php bin/console pim:installer:assets --clean --env=dev`
8. Run asset installer `docker-compose run -u www-data --rm php bin/console asset:install --clean --env=dev`
9. Run webpack `docker-compose run --rm node yarn run webpack`
After webpack is finished seems there is asset install issue.
![lejupielāde](https://user-images.githubusercontent.com/1228091/84120511-943de500-aa3e-11ea-9869-93bda15b67fa.png)

**Expected Result**
Extension is installed and is working in docker setup

**Actual Result**
Extension is not available in admin panel and even in command line interface

Can anyone help or give suggestion how to properly install Textmaster extension for Akeneo 4.0.6 on docker setup.
Thanks!

**Comment by huynguyen93** [comment]
Hi @kilis ,

From your screenshot, I think this error is not related to akeneo-extension.
Can you try remove `PimTextmasterBundle` from the project and install the assets again to see it the problem still occurs?

I think I had this kind of issue once in a while, I'm not sure 100% but I had to do `docker-compose down` to clear the cache in elasticsearch and then it will work again.

**Comment by kilis** [comment]
Hello, @huynguyen93 
Seems i managed to install in docker correctly.
Please update README file with these commands for docker setup
1. Add extension `docker-compose run --rm php php -d memory_limit=4G /usr/local/bin/composer require textmaster/akeneo-extension:~4.0`
2. Create a file and folder in project root `config/routes/routes.yml`
3. Add content 
```
textmaster:
  resource: "@PimTextmasterBundle/Resources/config/routing.yml"
  
```
4. Add new line in `config/bundles.php`
` Pim\Bundle\TextmasterBundle\PimTextmasterBundle::class => ['dev' => true, 'test' => true, 'prod' => true],
`
5. Generate cache run `make cache`
6. Generate assets run `make assets`
7. Generate javascript assets `make javascript-dev or make javascript-prod`
Then it showed correctly in admin panel.
Thanks!

**Comment by huynguyen93** [comment]
Thank you @kilis , I updated the README for branch 4.0!
