### ISSUE TITLE
Problem during upgrade from v3.0.x to v3.2.x.

### ISSUE THREAD

**Issue by anthonyDevSf** [textmaster/akeneo-extension#71]
Hello,

After having retrieved the last tag (3.2.9), we have the same problem but on the "textmaster_project" table (cf. https://github.com/textmaster/akeneo-extension/issues/69)

The error raised is:

`SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'created_at' at row 1`

Is it possible to modify the doctrine schema for this table like the tag 3.2.9?

Thanks in advance.

**Comment by heleyboo** [comment]
Hi @anthonyDevSf 

Here is the release for this:  https://github.com/textmaster/akeneo-extension/releases/tag/v3.2.10
