### ISSUE TITLE
Problem during upgrade from v3.2.x to v4.0.x.

### ISSUE THREAD

**Issue by anthonyDevSf** [textmaster/akeneo-extension#78]
Hello,

After having retrieved the last tag (4.0.0) I have an error when I launch the doctrine schema update.

The error raised:

`An exception occurred while executing 'ALTER TABLE textmaster_project CHANGE created_at created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime)'':
SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value
`

Indeed between 3.2.14 and 4.0.0 tags the doctrine schema for project and document entities is not the same.
It is possible to modifiy the doctrine schema like 3.2.14 tag ?

Thanks in advance.

**Comment by heleyboo** [comment]
hi @anthonyDevSf 

I've fixed it. You can checkout new tag v4.0.1.
